# This file was generated by GoReleaser. DO NOT EDIT.
cask "actionlint" do
  version "1.14.0"

  on_macos do
    on_arm do
      sha256 "20e66b0d6622a3c6a1bcdff1503a19003e6853a59e104cae68ab879b8e19d936"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8588ae816c7221df54f0779749946b8ebbd536c8c1e0a6e7044d4bc4ed5ccf01"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fa0540054f9a80f0ab006657559fd7b511a8680e93d2c0b7f581bb80f9a2ab47"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "14151358d71bdf746bb360480dc145ee241c16ce2807e7368e6bddabbec34da6"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "actionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://actionlint.kjanat.dev"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "shellcheck",
    ]

  binary "actionlint"
  manpage "man/actionlint.1"

  # No zap stanza required
end
