# This file was generated by GoReleaser. DO NOT EDIT.
cask "actionlint" do
  version "1.15.0"

  on_macos do
    on_arm do
      sha256 "c384a80faa2a373833719cac19ce30eaaa0082f91e57cfb5339b85ae9f0a139d"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
    on_intel do
      sha256 "aaaf826f1037f9dbcb56f66d6f15bd7455095d0674b6663d4b9601f1bfe070eb"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
  end
  on_linux do
    on_arm do
      sha256 "47da14d07edd9d0a285c1e6b31e66d0af878c6fcf237600a644df18accbc8d15"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
    on_intel do
      sha256 "003a4772e98194099e7cc31eee8d85991b0d380b7960cf91d5b6e7614c6f61d1"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
  end

  name "actionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://actionlint.kjanat.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actionlint"
  manpage "man/actionlint.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actionlint"]
    end
  end
  generate_completions_from_executable "actionlint", "-completion",
    base_name: "actionlint",
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
