# This file was generated by GoReleaser. DO NOT EDIT.
cask "actionlint" do
  version "1.16.1"

  on_macos do
    on_arm do
      sha256 "2e00bd1288aa8461674222f17b7439e4e8bb79f86e5ee0230d3dffbd131b017f"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
    on_intel do
      sha256 "dd054fd309bfcab89586f40c6a11d4fa264ce770af1210fad2d9c9756ad3d5f3"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
  end
  on_linux do
    on_arm do
      sha256 "8727b6749053bd7a910ce816117328dd9a3b9ed8a212129ee2ea6b0acb2cd812"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
    on_intel do
      sha256 "d566eee8af147ee1fa24ee204e1a171fcf8b5ce40e267c39a7383c7f20e6236d"
      url "https://github.com/kjanat/actionlint/releases/download/v#{version}/actionlint_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kjanat/actionlint/"
    end
  end

  name "actionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://actionlint.kjanat.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actionlint"
  manpage "man/actionlint.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actionlint"]
    end
  end
  generate_completions_from_executable "actionlint", "-completion",
    base_name: "actionlint",
    shells: [:bash, :zsh, :fish, :pwsh]

  # No zap stanza required
end
